# Generated by Django 5.0.7 on 2024-08-06 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panditji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('pooja_type', models.CharField(max_length=100)),
                ('poojan_samagri', models.BooleanField(default=False)),
                ('mobilenumber', models.CharField(max_length=13)),
                ('panditji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.panditji')),
            ],
            options={
                'unique_together': {('panditji', 'date', 'time')},
            },
        ),
    ]
