# Generated by Django 5.0.7 on 2024-08-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panditji',
            name='username',
        ),
    ]
