# Generated by Django 5.0.7 on 2024-08-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_panditji_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration_hours',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
